export const COUNTRIES = [
  { code: 'AF', flag: '🇦🇫', name: 'Afghanistan', callingCode: '+93' },
  { code: 'AL', flag: '🇦🇱', name: 'Albania', callingCode: '+355' },
  { code: 'DZ', flag: '🇩🇿', name: 'Algeria', callingCode: '+213' },
  { code: 'AD', flag: '🇦🇩', name: 'Andorra', callingCode: '+376' },
  { code: 'AO', flag: '🇦🇴', name: 'Angola', callingCode: '+244' },
  { code: 'AR', flag: '🇦🇷', name: 'Argentina', callingCode: '+54' },
  { code: 'AM', flag: '🇦🇲', name: 'Armenia', callingCode: '+374' },
  { code: 'AU', flag: '🇦🇺', name: 'Australia', callingCode: '+61' },
  { code: 'AT', flag: '🇦🇹', name: 'Austria', callingCode: '+43' },
  { code: 'AZ', flag: '🇦🇿', name: 'Azerbaijan', callingCode: '+994' },
  { code: 'BD', flag: '🇧🇩', name: 'Bangladesh', callingCode: '+880' },
  { code: 'BY', flag: '🇧🇾', name: 'Belarus', callingCode: '+375' },
  { code: 'BE', flag: '🇧🇪', name: 'Belgium', callingCode: '+32' },
  { code: 'BR', flag: '🇧🇷', name: 'Brazil', callingCode: '+55' },
  { code: 'BG', flag: '🇧🇬', name: 'Bulgaria', callingCode: '+359' },
  { code: 'CA', flag: '🇨🇦', name: 'Canada', callingCode: '+1' },
  { code: 'CN', flag: '🇨🇳', name: 'China', callingCode: '+86' },
  { code: 'DK', flag: '🇩🇰', name: 'Denmark', callingCode: '+45' },
  { code: 'EG', flag: '🇪🇬', name: 'Egypt', callingCode: '+20' },
  { code: 'FI', flag: '🇫🇮', name: 'Finland', callingCode: '+358' },
  { code: 'FR', flag: '🇫🇷', name: 'France', callingCode: '+33' },
  { code: 'DE', flag: '🇩🇪', name: 'Germany', callingCode: '+49' },
  { code: 'GR', flag: '🇬🇷', name: 'Greece', callingCode: '+30' },
  { code: 'HK', flag: '🇭🇰', name: 'Hong Kong', callingCode: '+852' },
  { code: 'HU', flag: '🇭🇺', name: 'Hungary', callingCode: '+36' },
  { code: 'IS', flag: '🇮🇸', name: 'Iceland', callingCode: '+354' },
  { code: 'IN', flag: '🇮🇳', name: 'India', callingCode: '+91' },
  { code: 'ID', flag: '🇮🇩', name: 'Indonesia', callingCode: '+62' },
  { code: 'IR', flag: '🇮🇷', name: 'Iran', callingCode: '+98' },
  { code: 'IQ', flag: '🇮🇶', name: 'Iraq', callingCode: '+964' },
  { code: 'IE', flag: '🇮🇪', name: 'Ireland', callingCode: '+353' },
  { code: 'IL', flag: '🇮🇱', name: 'Israel', callingCode: '+972' },
  { code: 'IT', flag: '🇮🇹', name: 'Italy', callingCode: '+39' },
  { code: 'JP', flag: '🇯🇵', name: 'Japan', callingCode: '+81' },
  { code: 'JO', flag: '🇯🇴', name: 'Jordan', callingCode: '+962' },
  { code: 'KE', flag: '🇰🇪', name: 'Kenya', callingCode: '+254' },
  { code: 'KR', flag: '🇰🇷', name: 'South Korea', callingCode: '+82' },
  { code: 'KW', flag: '🇰🇼', name: 'Kuwait', callingCode: '+965' },
  { code: 'LU', flag: '🇱🇺', name: 'Luxembourg', callingCode: '+352' },
  { code: 'MY', flag: '🇲🇾', name: 'Malaysia', callingCode: '+60' },
  { code: 'MX', flag: '🇲🇽', name: 'Mexico', callingCode: '+52' },
  { code: 'NP', flag: '🇳🇵', name: 'Nepal', callingCode: '+977' },
  { code: 'NL', flag: '🇳🇱', name: 'Netherlands', callingCode: '+31' },
  { code: 'NZ', flag: '🇳🇿', name: 'New Zealand', callingCode: '+64' },
  { code: 'NG', flag: '🇳🇬', name: 'Nigeria', callingCode: '+234' },
  { code: 'NO', flag: '🇳🇴', name: 'Norway', callingCode: '+47' },
  { code: 'PK', flag: '🇵🇰', name: 'Pakistan', callingCode: '+92' },
  { code: 'PH', flag: '🇵🇭', name: 'Philippines', callingCode: '+63' },
  { code: 'PL', flag: '🇵🇱', name: 'Poland', callingCode: '+48' },
  { code: 'PT', flag: '🇵🇹', name: 'Portugal', callingCode: '+351' },
  { code: 'QA', flag: '🇶🇦', name: 'Qatar', callingCode: '+974' },
  { code: 'RO', flag: '🇷🇴', name: 'Romania', callingCode: '+40' },
  { code: 'RU', flag: '🇷🇺', name: 'Russia', callingCode: '+7' },
  { code: 'SA', flag: '🇸🇦', name: 'Saudi Arabia', callingCode: '+966' },
  { code: 'SG', flag: '🇸🇬', name: 'Singapore', callingCode: '+65' },
  { code: 'ZA', flag: '🇿🇦', name: 'South Africa', callingCode: '+27' },
  { code: 'ES', flag: '🇪🇸', name: 'Spain', callingCode: '+34' },
  { code: 'LK', flag: '🇱🇰', name: 'Sri Lanka', callingCode: '+94' },
  { code: 'SE', flag: '🇸🇪', name: 'Sweden', callingCode: '+46' },
  { code: 'CH', flag: '🇨🇭', name: 'Switzerland', callingCode: '+41' },
  { code: 'TW', flag: '🇹🇼', name: 'Taiwan', callingCode: '+886' },
  { code: 'TH', flag: '🇹🇭', name: 'Thailand', callingCode: '+66' },
  { code: 'TR', flag: '🇹🇷', name: 'Turkey', callingCode: '+90' },
  { code: 'UA', flag: '🇺🇦', name: 'Ukraine', callingCode: '+380' },
  { code: 'AE', flag: '🇦🇪', name: 'United Arab Emirates', callingCode: '+971' },
  { code: 'GB', flag: '🇬🇧', name: 'United Kingdom', callingCode: '+44' },
  { code: 'US', flag: '🇺🇸', name: 'United States', callingCode: '+1' },
  { code: 'VN', flag: '🇻🇳', name: 'Vietnam', callingCode: '+84' },
];